# Generated by Django 5.0.6 on 2024-06-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzapp', '0002_remove_question_op5'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_count', models.IntegerField(default=1)),
            ],
        ),
    ]
